### PR TITLE
Promise.all polyfill implementation

### PR DESCRIPTION
**Pull request by Gvinod1991**
Added the polyfill for the Promise.all with examples. Here is the working [codesanbox](https://codesandbox.io/s/promise-all-polyfill-rz24cp-rz24cp) .

### CODE REVIEW

**Comment by ishwarrimal** [comment]
Thanks for the contribution, works perfectly for all the promises, but there is a small use case that you need to handle.
This will not work for an input which is not a promise. 
Promise.all() handles the case in which if you provide a string or any other type, it is still resolved.

Example:
```javascript
  const promise1 = Promise.resolve(3);
  const promise2 = 42;
  const promise3 = new Promise((resolve, reject) => {
    setTimeout(resolve, 100, 'foo');
  });
  
  Promise.all([promise1, promise2, promise3]).then((values) => {
    console.log(values);
  });
```

**Comment by Gvinod1991** [comment]
Handled use case of input provided to promise.all polyfill other than promise. Here is the working [codesanbox](https://codesandbox.io/s/promise-all-polyfill-rz24cp-rz24cp) .

**Comment by ishwarrimal** [comment]
Instead of all these checks, you can simply use
```javascript
Promise.resolve(promises[i])
                .then(res...
```
This will handle the case of non-promise variables.

Can you try that once again?

**Comment by Gvinod1991** [comment]
Non promise input to promise.all polyfill handled with code refactor using the Promise.resolve instead of checking type of input is promise or not. So polyfill function code looks cleaner. Thanks for your feedback @ishwarrimal

**Review by ishwarrimal — APPROVED** [review]

**Pull request merged**
