### PR TITLE
Adding contributors in readme.md

### LINKED ISSUE #21: Add names and profile link of existing contributors to this repo.
Add names and profile link of contributors to this repo.

At the bottom of the main readme, we need to add the names and link of the contributors of this repo.

### PR DESCRIPTION
**Pull request by someoneme**

### CODE REVIEW

**Comment by ishwarrimal** [comment]
Can you please add `https://github.com/nikitabarnawal` to this list too? For some reason her contributions are not showing up...and don't forget to add yourself too.

**Comment by someoneme** [comment]
@ishwarrimal can you check now

**Comment by someoneme** [comment]
Can you check @ishwarrimal

**Comment by someoneme** [comment]
Can you check this @ishwarrimal

**Review by ishwarrimal — APPROVED** [review]

**Pull request merged**
